services:
  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cliston
    ports:
      - "8100:8100"
    volumes:
      # Mount data directory to persist vectorstore, conversation cache, and resources
      - ./cliston/data:/app/cliston/data
    environment:
      - PYTHONUNBUFFERED=1
      - EMBEDDER_URL=http://embedder-service:8009
      - EMBEDDER_TIMEOUT_SECONDS=120
      - EMBEDDER_BATCH_SIZE=32

    env_file:
      - .env
    restart: unless-stopped
